version: "3.9"

services:
  # CONSUL AGENTS
  consul-agent-1:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    ports:
      - "8081:8080"
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-3:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  # CONSUL SERVERS
  consul-server-1:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  # CONSUL SERVERS BOOTSTRAP
  consul-server-bootstrap:
    image: consul:latest
    environment:
      - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  # DEMO APP
  server:
    container_name: server
    build:
      context: .
    restart: on-failure
    env_file:
      - ./server.env
    depends_on:
      - consul-agent-1
    network_mode: service:consul-agent-1 # Using same network namespace as agent-1

  client:
    container_name: client
    build:
      context: .
    restart: on-failure
    env_file:
      - ./client.env
    depends_on:
      - consul-agent-2
    network_mode: service:consul-agent-2 # Using same network namespace as agent-2

networks:
  consul-demo:
    name: consul-demo